import localFont from "next/font/local";
import { StoreProvider } from "@/Redux/Provider/StoreProvider";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import MainMenu from "@/Components/Menu/MainMenu";
// const geistSans = localFont({
//   src: "../../public/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",${geistSans.variable}
// });
const geistMono = localFont({
  src: "../../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "RJ Land",
  description: "Generated by create Rezj",
};
const yekan= localFont({src:"../../../public/fonts/yekan-bakh-regular.ttf"})

import React from 'react'

const layout = ({ children }) => {
  return (
    <div className={` ${geistMono.variable} ${yekan.className}`}>
         <Header/>
        <MainMenu />

      <StoreProvider>
        {children}
        </StoreProvider>
        <Footer/>
      
    </div>
  )
}

export default layout
