import localFont from "next/font/local";
import { StoreProvider } from "@/Redux/Provider/StoreProvider";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import MainMenu from "@/Components/Menu/MainMenu";
import React, { Suspense } from "react";
import LowerPart from "@/Components/LowerPart/LowerPart";

const geistMono = localFont({
  src: "../../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
<link rel="icon" href="/Images/image-Header/footerlogo2.webp" />;

export const metadata = {
  title: "RJ Land",
  description: "Generated by Reza Khodadadi",
};
const yekan = localFont({
  src: "../../../public/fonts/yekan-bakh-regular.ttf",
});

export const revalidate = 2628000;

const layout = ({ children }) => {
  return (
    <div className={` ${geistMono.variable} ${yekan.className}`}>
      <Suspense>
        <Header />
      </Suspense>
      <LowerPart />
      <Suspense>
        <MainMenu />
      </Suspense>
      <StoreProvider>{children}</StoreProvider>
      <Footer />
    </div>
  );
};

export default layout;
