import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "@/Redux/Provider/StoreProvider";

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "RJ Land",
  description: "Generated by create Rezj",
};
export const revalidate = 2628000  

const yekan = localFont({ src: "../../public/fonts/yekan-bakh-regular.ttf" });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} ${yekan.className}`}>
      <meta name="author" content="Reza Khodadadi" />
      <link rel="icon" href="/logo/TitleLogo2.png" />

        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
