import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "@/Redux/Provider/StoreProvider";

// const geistSans = localFont({
//   src: "../../public/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",${geistSans.variable}
// });
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "RJ Land",
  description: "Generated by create Rezj",
};
const yekan = localFont({ src: "../../public/fonts/yekan-bakh-regular.ttf" });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} ${yekan.className}`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
